import 'dotenv/config';
import { Client, GatewayIntentBits, EmbedBuilder, Events, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';
import { createClient } from '@supabase/supabase-js';
const e=process.env;
for(const k of ['DISCORD_TOKEN','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','BOT_OWNER_ID']) if(!e[k]) throw new Error('Missing '+k);
const db=createClient(e.SUPABASE_URL!,e.SUPABASE_SERVICE_ROLE_KEY!);
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const PREFIX=e.PREFIX||'UwU', START=Number(e.STARTING_BALANCE||1000), MAX_CF=Number(e.MAX_CF_BET||500000);
const fmt=(n:number)=>n>=1e9?(n/1e9).toFixed(2).replace(/\.00$/,'')+' billion':n>=1e6?(n/1e6).toFixed(2).replace(/\.00$/,'')+' million':n>=1e3?(n/1e3).toFixed(2).replace(/\.00$/,'')+'k':n.toLocaleString('en-US');
const emb=(t:string,d:string)=>new EmbedBuilder().setTitle(t).setDescription(d).setColor(0xff8ac8).setTimestamp();
async function user(id:string){let {data}=await db.from('users').select('*').eq('discord_user_id',id).maybeSingle();if(data)return data;const r=await db.from('users').insert({discord_user_id:id,balance:START}).select().single();if(r.error)throw r.error;return r.data}
async function guild(id:string){let {data}=await db.from('guild_settings').select('*').eq('guild_id',id).maybeSingle();if(data)return data;const r=await db.from('guild_settings').insert({guild_id:id,prefix:PREFIX,cash_name:'UwU'}).select().single();if(r.error)throw r.error;return r.data}
async function add(id:string,amount:number,type:string){const u=await user(id),next=Number(u.balance)+amount;if(next<0)throw Error('INSUFFICIENT');const r=await db.from('users').update({balance:next,updated_at:new Date().toISOString()}).eq('discord_user_id',id);if(r.error)throw r.error;await db.from('transactions').insert({discord_user_id:id,type,amount});return next}
async function cd(id:string,c:string,seconds:number){const now=Date.now(),r=await db.from('cooldowns').select('expires_at').eq('discord_user_id',id).eq('command',c).maybeSingle();if(r.data&&new Date(r.data.expires_at).getTime()>now)return Math.ceil((new Date(r.data.expires_at).getTime()-now)/1000);await db.from('cooldowns').upsert({discord_user_id:id,command:c,expires_at:new Date(now+seconds*1000).toISOString()});return 0}
client.once(Events.ClientReady,c=>console.log('UWU ready: '+c.user.tag));
client.on(Events.GuildCreate,g=>guild(g.id).catch(console.error));
client.on(Events.MessageCreate,async m=>{if(m.author.bot||!m.guild)return;try{const s=await guild(m.guild.id),p=s.prefix;if(!m.content.toLowerCase().startsWith(p.toLowerCase()))return;const a=m.content.slice(p.length).trim().split(/\s+/),cmd=(a.shift()||'').toLowerCase();if(!cmd)return;const u=await user(m.author.id);if(u.disabled&&!['useron','userstatus'].includes(cmd))return void m.reply({embeds:[emb('Account Disabled','Your UWU account is disabled.')]});if(cmd==='start'){if(u.started)return void m.reply('Your UWU account is already active.');await db.from('users').update({started:true}).eq('discord_user_id',m.author.id);return void m.reply({embeds:[emb('UWU Account','Account activated. Starting balance: '+fmt(START)+' '+s.cash_name)]})}if(!u.started&&!['help'].includes(cmd))return void m.reply('Use '+p+' start first.');
if(cmd==='bal'||cmd==='cash')return void m.reply({embeds:[emb('Global Wallet','Balance: '+fmt(u.balance)+' '+s.cash_name+'\nGlobal across every server.\nStatus: Active')]});
if(cmd==='help')return void m.reply({embeds:[emb('UWU Commands',p+' start | bal | daily | work | mine | hunt | fish | cf amount | transfer @user amount | lb | inv | zoo | weapons | drop amount')]});
if(['daily','work','mine','hunt','fish'].includes(cmd)){const sec:any={daily:86400,work:1800,mine:300,hunt:900,fish:600};const left=await cd(m.author.id,cmd,sec[cmd]);if(left)return void m.reply('Try again in '+left+'s.');const range:any={daily:[500,1500],work:[250,900],mine:[100,700],hunt:[150,1000],fish:[100,800]}[cmd];const reward=Math.floor(Math.random()*(range[1]-range[0]+1))+range[0],bal=await add(m.author.id,reward,cmd);return void m.reply({embeds:[emb(cmd.toUpperCase(),'Earned '+fmt(reward)+' '+s.cash_name+'\nBalance: '+fmt(bal)+' '+s.cash_name)]})}
if(cmd==='cf'){const bet=Math.floor(Number(a[0]));if(!Number.isFinite(bet)||bet<1||bet>MAX_CF)return void m.reply('Usage: '+p+' cf amount. Max '+fmt(MAX_CF));if(Number(u.balance)<bet)return void m.reply('Insufficient balance.');const win=Math.random()<.5,bal=await add(m.author.id,win?bet:-bet,'coinflip');return void m.reply({embeds:[emb(win?'COIN FLIP — WIN':'COIN FLIP — LOSS','Result: '+(win?'HEADS':'TAILS')+'\n'+(win?'Won':'Lost')+' '+fmt(bet)+' '+s.cash_name+'\nBalance: '+fmt(bal)+' '+s.cash_name)]})}
if(cmd==='transfer'){const t=m.mentions.users.first(),amount=Math.floor(Number(a[1]||a[0]));if(!t||t.bot||!Number.isFinite(amount)||amount<1)return void m.reply('Usage: '+p+' transfer @user amount');if(Number(u.balance)<amount)return void m.reply('Insufficient balance.');await user(t.id);await add(m.author.id,-amount,'transfer_out');await add(t.id,amount,'transfer_in');return void m.reply({embeds:[emb('Transfer Complete','Sent '+fmt(amount)+' '+s.cash_name+' to <@'+t.id+'>.')]})}
if(cmd==='lb'){const r=await db.from('users').select('discord_user_id,balance').eq('disabled',false).order('balance',{ascending:false}).limit(25);const lines=(r.data||[]).map((x:any,i:number)=>(i+1)+'. <@'+x.discord_user_id+'> — '+fmt(x.balance)+' '+s.cash_name).join('\n')||'No users yet.';return void m.reply({embeds:[emb('Global Leaderboard',lines)]})}
if(['inv','zoo','weapons'].includes(cmd)){const kind=cmd==='zoo'?'animal':cmd==='weapons'?'weapon':null;let q:any=db.from('inventory').select('quantity,catalog_items(name,emoji,rarity,kind)').eq('discord_user_id',m.author.id);if(kind)q=q.eq('catalog_items.kind',kind);const r=await q;const lines=(r.data||[]).filter((x:any)=>x.quantity>0).map((x:any)=>x.catalog_items.emoji+' '+x.catalog_items.name+' x'+x.quantity+' — '+x.catalog_items.rarity).join('\n');return void m.reply({embeds:[emb(kind==='animal'?'Zoo':kind==='weapon'?'Weapons':'Inventory',lines||'Nothing collected yet.')]})}
if(['addcash','removecash','setcash','useroff','useron','shutdown','drop'].includes(cmd)){if(m.author.id!==e.BOT_OWNER_ID)return void m.reply('Owner only.');if(cmd==='shutdown'){const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('shutdown_yes').setLabel('Shutdown').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('shutdown_no').setLabel('Cancel').setStyle(ButtonStyle.Secondary));return void m.reply({embeds:[emb('Shutdown','Confirm UWU shutdown?')],components:[row]})}const t=m.mentions.users.first();if(cmd==='drop'){const amount=Math.floor(Number(a[0]));if(!amount||amount<1)return void m.reply('Usage: '+p+' drop amount');const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('drop_'+amount).setLabel('Claim').setStyle(ButtonStyle.Success));return void m.channel.send({embeds:[emb('UWU Cash Drop',fmt(amount)+' '+s.cash_name+' is available to claim.')],components:[row]})}if(!t)return void m.reply('Mention a user.');await user(t.id);if(cmd==='useroff'||cmd==='useron'){await db.from('users').update({disabled:cmd==='useroff'}).eq('discord_user_id',t.id);return void m.reply(cmd==='useroff'?'User disabled.':'User enabled.')}const amount=Math.floor(Number(a[1]||a[0]));if(!Number.isFinite(amount)||amount<0)return void m.reply('Invalid amount.');const old=Number((await user(t.id)).balance),delta=cmd==='addcash'?amount:cmd==='removecash'?-amount:amount-old;await add(t.id,delta,'owner_'+cmd);await db.from('audit_logs').insert({actor_user_id:m.author.id,target_user_id:t.id,amount:delta,action:cmd});return void m.reply(cmd+' completed.')}
}catch(err){console.error(err);await m.reply('Internal error. Check logs.').catch(()=>{})}});
client.on(Events.InteractionCreate,async i=>{if(!i.isButton())return;if(i.customId==='shutdown_no')return void i.update({content:'Shutdown cancelled.',embeds:[],components:[]});if(i.customId==='shutdown_yes'){if(i.user.id!==e.BOT_OWNER_ID)return void i.reply({content:'Owner only.',ephemeral:true});await i.update({content:'UWU shutting down...',embeds:[],components:[]});await client.destroy();process.exit(0)}if(i.customId.startsWith('drop_')){const amount=Number(i.customId.slice(5)),key='drop:'+i.message.id;const exists=await db.from('transactions').select('id').eq('discord_user_id',i.user.id).eq('type',key).maybeSingle();if(exists.data)return void i.reply({content:'Already claimed.',ephemeral:true});await user(i.user.id);await add(i.user.id,amount,key);return void i.reply({content:'Claimed '+fmt(amount)+' UwU!',ephemeral:true})}});
process.on('SIGTERM',()=>{client.destroy().finally(()=>process.exit(0))});
client.login(e.DISCORD_TOKEN);